services:
  redis-1:
    image: redis:7.4
    ports: ["7001:7001", "17001:17001"]
    command: >
      redis-server --port 7001
      --cluster-enabled yes
      --cluster-config-file nodes-1.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 127.0.0.1
      --cluster-announce-port 7001
      --cluster-announce-bus-port 17001
      --appendonly yes
  redis-2:
    image: redis:7.4
    ports: ["7002:7002", "17002:17002"]
    command: >
      redis-server --port 7002
      --cluster-enabled yes
      --cluster-config-file nodes-2.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 127.0.0.1
      --cluster-announce-port 7002
      --cluster-announce-bus-port 17002
      --appendonly yes
  redis-3:
    image: redis:7.4
    ports: ["7003:7003", "17003:17003"]
    command: >
      redis-server --port 7003
      --cluster-enabled yes
      --cluster-config-file nodes-3.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 127.0.0.1
      --cluster-announce-port 7003
      --cluster-announce-bus-port 17003
      --appendonly yes
